In [1]:
import numpy as np

In [2]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
arr[10]

10

In [4]:
arr[4:7]

array([4, 5, 6])

In [5]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [7]:
arr_slice[1] = 345
arr

array([  0,   1,   2,   3,   4,  12, 345,  12,   8,   9,  10,  11,  12,
        13,  14])

In [8]:
arr_slice[:] = 64
arr_slice

array([64, 64, 64])

In [9]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2d[0]

array([1, 2, 3])

In [12]:
arr2d[0][2]

3

In [13]:
arr2d[0, 2]

3

In [14]:
arr3d = np.array([[[1, 2, 3], 
                   [4, 5, 6]], 
                  
                  [[7, 8, 9], 
                   [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
arr3d.shape

(2, 2, 3)

In [16]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])